// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/mhrivnak/kni-operator/pkg/apis/kni/v1alpha1.KNICluster":       schema_pkg_apis_kni_v1alpha1_KNICluster(ref),
		"github.com/mhrivnak/kni-operator/pkg/apis/kni/v1alpha1.KNIClusterSpec":   schema_pkg_apis_kni_v1alpha1_KNIClusterSpec(ref),
		"github.com/mhrivnak/kni-operator/pkg/apis/kni/v1alpha1.KNIClusterStatus": schema_pkg_apis_kni_v1alpha1_KNIClusterStatus(ref),
	}
}

func schema_pkg_apis_kni_v1alpha1_KNICluster(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KNICluster is the Schema for the kniclusters API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/mhrivnak/kni-operator/pkg/apis/kni/v1alpha1.KNIClusterSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/mhrivnak/kni-operator/pkg/apis/kni/v1alpha1.KNIClusterStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/mhrivnak/kni-operator/pkg/apis/kni/v1alpha1.KNIClusterSpec", "github.com/mhrivnak/kni-operator/pkg/apis/kni/v1alpha1.KNIClusterStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_kni_v1alpha1_KNIClusterSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KNIClusterSpec defines the desired state of KNICluster",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_kni_v1alpha1_KNIClusterStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KNIClusterStatus defines the observed state of KNICluster",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
